### ISSUE TITLE
Plugin UI too small on a 4k screen

### ISSUE THREAD

**Issue by amadeusp** [Wasted-Audio/wstd-eq#1]
# Issue(s)
* The plugin is very small on my 4k screen with a resolution of 3840 x 2400
* The scrollbars overlap the plugin UI

# Expected behavior
* The plugin would be displayed in a 200% scale or (ideally) would allow its UI to be scaled
* The scrollbars would be hidden

# Basic system information
* Operating system: Manjaro Linux x86_64
* Kernel: Manjaro Linux x86_64
* Host: ThinkPad Z16 Gen 1
* Desktop environment: GNOME 43.4
* Display protocol: Wayland
* Audio server: PipeWire
* Session and policy manager: WirePlumber
* Digital audio workstation: Bitwig Studio (Flatpak)

# Screen grabs
![WSTD_EQ-Screenshot from 2023-04-28 05-23-01](https://user-images.githubusercontent.com/2808562/235007424-7af70cd3-cc73-437d-8c17-72b980601f5b.png)
![WSTD_EQ-Screenshot from 2023-04-28 05-23-06](https://user-images.githubusercontent.com/2808562/235007420-15e31905-c474-47a7-8550-7c86d5da376c.png)

**Comment by dromer** [comment]
Hey there. This week I've pushed some updates for HiDPI screens that should make scaling work _much_ better!

**Comment by amadeusp** [comment]
@dromer This is great news! Thank you so much! On your website the plugin download seems to be dated 23 February. How can I get and test this new version you have released?

**Comment by dromer** [comment]
I _just_ updated the build on itch.io - you should be able to download the latest version, which is v0.3.2

**Comment by dromer** [comment]
@amadeusp can you confirm this resolves the issue?

**Comment by amadeusp** [comment]
@dromer Yes, I am happy to confirm that the EQ is now behaving perfectly fine. :blush:

**Comment by dromer** [comment]
Thnx!
