### ISSUE TITLE
Description in README.md on how to compile?

### ISSUE THREAD

**Issue by 38github** [Wasted-Audio/wstd-eq#2]
Are you interested in providing this? I installed hvcc but found no commands to use so I looked in ACTION and found the build process but the commands gave me errors or warnings about abstract directories or paths, etc.

It would be **very** appreciated.

**Comment by dromer** [comment]
Did you load all submodules? Warnings should be fine, but errors should be reported.

At the moment building is considered "advanced" and following the gh-actions should be correct (it's what I use locally as well).
I'm not yet ready to provide full build docs, although things shouldn't be that difficult to figure out.
